import {
  Archive,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bookmark,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleHelp,
  Clock3,
  CloudOff,
  Coffee,
  Compass,
  Cookie,
  Cpu,
  CreditCard,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileDown,
  FileText,
  Folder,
  FolderInput,
  Gift,
  GraduationCap,
  Grid2X2,
  HardDrive,
  Heart,
  History,
  Home,
  Hourglass,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  Layers,
  Library,
  List,
  Loader2,
  LogIn,
  MapPin,
  Maximize2,
  Music,
  Palette,
  Plane,
  PlayCircle,
  Plus,
  RefreshCw,
  RotateCw,
  ScanLine,
  Scissors,
  Search,
  Settings,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Smile,
  Sparkles,
  Tag,
  Tags,
  Trash2,
  User,
  Utensils,
  Video,
  Wifi,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { CSSProperties } from 'react';

const ICONS = {
  alert: AlertTriangle,
  archive: Archive,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  book: BookOpen,
  bookmark: Bookmark,
  briefcase: Gift,
  camera: ImageIcon,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clock: Clock3,
  circleHelp: CircleHelp,
  cloudOff: CloudOff,
  coffee: Coffee,
  compass: Compass,
  cookie: Cookie,
  cpu: Cpu,
  creditCard: CreditCard,
  download: Download,
  edit: Edit3,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileDown: FileDown,
  fileText: FileText,
  folder: Folder,
  folderInput: FolderInput,
  gift: Gift,
  graduationCap: GraduationCap,
  grid: Grid2X2,
  hardDrive: HardDrive,
  heart: Heart,
  history: History,
  home: Home,
  hourglass: Hourglass,
  image: ImageIcon,
  inbox: Inbox,
  key: KeyRound,
  layers: Layers,
  library: Library,
  list: List,
  loader: Loader2,
  login: LogIn,
  mapPin: MapPin,
  maximize: Maximize2,
  music: Music,
  palette: Palette,
  plane: Plane,
  playLg: PlayCircle,
  plus: Plus,
  refresh: RefreshCw,
  rotateCw: RotateCw,
  scan: ScanLine,
  scissors: Scissors,
  search: Search,
  searchX: Search,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shirt: Shirt,
  shoppingBag: ShoppingBag,
  smile: Smile,
  sparkles: Sparkles,
  tag: Tag,
  tags: Tags,
  trash: Trash2,
  user: User,
  utensils: Utensils,
  video: Video,
  wifi: Wifi,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 16,
  stroke = 2,
  className,
  style,
}: {
  name: IconName;
  size?: number;
  stroke?: number;
  className?: string;
  style?: CSSProperties | null;
}) {
  const Cmp = ICONS[name] ?? Bookmark;
  return <Cmp aria-hidden="true" className={className} size={size} strokeWidth={stroke} style={style ?? undefined} />;
}
